version: "3"
services:
  web:
    build: .
    ports:
      - "63154:3000"
    environment:
      - REDIS_URL=redis://redis/
      - Authorization=
      - SentryDSN=
      - PGHOST=db
      - PGUSER=matsuri_icu
      - PGPASSWORD=matsuri_icu
      - PGDATABASE=matsuri_icu
      - recaptcha=
    links:
      - "redis"
      - "db"
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:13-alpine"
    volumes:
      - /home/admin/Apps/api.matsuri.icu/data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=matsuri_icu
      - POSTGRES_HOST_AUTH_METHOD=trust
